apiVersion: v1
kind: Service
metadata:
  name:  mydevops-rtp-service
  namespace: mydevops2023
spec:
  type: LoadBalancer
  selector:
    app: mydevops-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000